In [256]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
import numpy as np

from sklearn.ensemble import RandomForestClassifier

from math import sqrt

from keras.models import Sequential
from keras.layers import CuDNNLSTM, Dense, Dropout, LSTM
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
#from keras.datasets import mnist

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler



In [257]:
currency_list = ['USDCHF1440',
                 #'GBPUSD1440',
    #'EURUSD1440', 
    #'USDJPY1440', 
    #'USDCAD1440', 
    #'AUDUSD1440', 
    #'NZDUSD1440',
                 #'GBPCHF1440',
    #'EURCHF1440', 
    #'CHFJPY1440', 
    #'CADCHF1440',
    #'AUDCHF1440', 
    #'NZDCHF1440', 
    #'EURGBP1440',
             #   'GBPCAD1440',
     #'GBPAUD1440', 
    #'EURJPY1440',
    #'EURCAD1440',
    #'EURAUD1440',
    #'EURNZD1440',
    #'CADJPY1440', 
    #'AUDJPY1440',
    #'NZDJPY1440',
    #'AUDCAD1440', 
    #'NZDCAD1440', 
                #'AUDNZD1440'
                ]



# for q in currency_list:
    
#     errors = []
    
#     for x in range(5):

#         currency = q.replace('1440','')

#         data = pd.read_excel('files/currency_training_data/' + currency +'_combine_data_dataframe.xlsx', sheet_name=0)
#         #data = data.head(695)


#         X = data.drop(columns=['Unnamed: 0', 
#                                'date_start',  'nextweek_class',


#                               ])



#         y = data['nextweek_class']

#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2 )



#         lnr= LinearRegression()
#         lnr.fit(X_train, y_train)
#         y_predict = lnr.predict(X_test)
        
        
#         error = sqrt(mean_squared_error(y_test, y_pred))
#         errors.append(error)
       
        
#     average_error = sum(errors)/len(errors)
       
#     print(q + " Linear regression Average " + str(average_error))
    
    
   


In [258]:
for q in currency_list:
    
    
    
    sequences = [1,]
    
    all_sequence_result = []
        
    for m in sequences:
    
        errors = []
        for x in range(2):
        
            currency = q.replace('1440','')

            data = pd.read_excel('files/currency_training_data/' + q +'_combine_data_dataframe.xlsx', sheet_name=0)
            #data = data.head(695)


            X = data.drop(columns=['Unnamed: 0', 
                                   'date_start',  'nextweek_class',


                                  ])



            y = data['nextweek_class']

            
#             X_scaler = RobustScaler(quantile_range=(10.0, 90.0),)
            
#             X_scaler.fit(X)
           
#             X = X_scaler.transform(X)
           
#             X = pd.DataFrame(X, columns = [q+"_class", q+'_volume'])
            

            #print(X)


            # after scaling the df, resulted in "scaled_dataset"





            result = []
            # for loop will walk for each of the 1500 rows
            for i in range(0,len(X)):
                # every group must have the same length, so if current loop position i + number 
                # of sequences is higher than df length, breaks
                if i+m <= len(X):
                    # this will add into the list as [[R1a,R1b...R1t],[R2a,R2b...R2t],...[R5a,R5b...R5t]]
                    result.append(X[i:i+m].values)
            # Converting to array + keras takes float32 better than 64
            train_x = np.array(result)
            #train_x  = train_x.astype('float32')
            # making the y into same length as X
            train_y = np.array(y.head(len(train_x)).values)

            #print(train_x.shape, train_y.shape)
            #print(train_x[len(train_x)-10])
            #print(train_y[len(train_x)-10])
            
            print(train_y)
            #train_x = tf.keras.utils.to_categorical(train_x,)
            #train_y = tf.keras.utils.to_categorical(train_y)
            print(train_y.shape)

            X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size = 0.01 )
             
           

            #X_train, X_val, y_train, y_val = train_test_split( X_train, y_train, test_size = 0.15 )

            tf.keras.backend.clear_session()

            #Initializing the classifier Network
            classifier = Sequential()

            #Adding the input LSTM network layer
            #classifier.add(CuDNNLSTM(128, input_shape=(X_train.shape[1:]), return_sequences=True))
            classifier.add(Dense(10, 
                                 #input_shape=(train_x.shape[1:]),
                                 input_dim= 3,
                                 #return_sequences=True,
                                 activation='relu'))
           
           
            classifier.add(Dense(10,  
                                 #return_sequences=True, 
                                 activation='relu')  )
            #classifier.add(LSTM(100,  return_sequences=True))
            

            #classifier.add(Dense(units = 1))
            classifier.add(Dense(1,  
                                 #return_sequences=False,
                                 activation='softmax'))
            #classifier.add(Dropout(0.2))
            #Adding a second LSTM network layer

            #classifier.add(LSTM(128))
            #Adding a dense hidden layer
            #classifier.add(Dense(64, activation='relu'))
            #classifier.add(Dropout(0.2))

            #Adding the output layer
            #classifier.add(Dense(35, activation='softmax'))

            #Compiling the network
            classifier.compile( loss='categorical_crossentropy',
                            optimizer=Adam(learning_rate=0.001, decay=1e-6),
                               metrics=['categorical_crossentropy']
                             )

            print(classifier.summary())

            #Fitting the data to the model
            history = classifier.fit(X_train,
                        y_train,
                        epochs=50,
                        validation_split=0.5,
                        batch_size=92
                                    )        

            #val_loss  = classifier.evaluate(X_test, y_test)
            #error = sqrt(val_loss)
            #errors.append(error)
            #plt.plot(history.history['loss'],'red')
            #plt.plot(history.history['val_loss'], 'blue')
            print('------------------------------------------------------------------------------------',x)
            
        
        #average_error = sum(errors)/len(errors)
        print(errors)
        print(q , "------------------------ RNN " , average_error)
        all_sequence_result.append(str(m)+" sequence" )
        all_sequence_result.append(average_error)


[2 2 6 ... 3 4 3]
(8881,)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                40        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/50
48/48 [==============================] - 2s 12ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_crossentropy: 4.1444e-07
Epoch 2/50
48/48 [==============================] - 0s 6ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_cross

48/48 [==============================] - 0s 4ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_crossentropy: 4.1444e-07
Epoch 36/50
48/48 [==============================] - 0s 4ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_crossentropy: 4.1444e-07
Epoch 37/50
48/48 [==============================] - 0s 4ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_crossentropy: 4.1444e-07
Epoch 38/50
48/48 [==============================] - 0s 4ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_crossentropy: 4.1444e-07
Epoch 39/50
48/48 [==============================] - 0s 4ms/step - loss: 4.1420e-07 - categorical_crossentropy: 4.1420e-07 - val_loss: 4.1444e-07 - val_categorical_crossentropy: 4.1444e-07
Epoch 40/50
48/48 [==============================] - 0s 4ms/step - 

Epoch 19/50
48/48 [==============================] - 0s 4ms/step - loss: 4.1295e-07 - categorical_crossentropy: 4.1295e-07 - val_loss: 4.1617e-07 - val_categorical_crossentropy: 4.1617e-07
Epoch 20/50
48/48 [==============================] - 0s 5ms/step - loss: 4.1295e-07 - categorical_crossentropy: 4.1295e-07 - val_loss: 4.1617e-07 - val_categorical_crossentropy: 4.1617e-07
Epoch 21/50
48/48 [==============================] - 0s 7ms/step - loss: 4.1295e-07 - categorical_crossentropy: 4.1295e-07 - val_loss: 4.1617e-07 - val_categorical_crossentropy: 4.1617e-07
Epoch 22/50
48/48 [==============================] - 0s 6ms/step - loss: 4.1295e-07 - categorical_crossentropy: 4.1295e-07 - val_loss: 4.1617e-07 - val_categorical_crossentropy: 4.1617e-07
Epoch 23/50
48/48 [==============================] - 0s 4ms/step - loss: 4.1295e-07 - categorical_crossentropy: 4.1295e-07 - val_loss: 4.1617e-07 - val_categorical_crossentropy: 4.1617e-07
Epoch 24/50
48/48 [==============================] - 0s

In [259]:
print(all_sequence_result)   
print(X_test[1])
classifier.predict(X_test)

['1 sequence', 11.038594784938683]
[[33244     4     4]]


array([[[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [

In [260]:
print(y_test)

[4 4 3 1 5 3 2 2 4 2 4 2 4 3 4 3 3 2 6 4 4 4 4 4 3 2 5 4 2 5 5 2 3 5 4 3 4
 5 4 2 3 4 2 1 5 5 4 2 2 5 3 5 5 2 4 5 2 5 2 3 4 2 2 2 5 3 3 3 2 3 3 4 5 4
 4 2 4 2 2 2 4 3 4 1 5 4 2 3 3]
